### ISSUE TITLE
Patchnotes screwup

### ISSUE THREAD

**Issue by PlainSys** [Plain-bot/plain-bot.github.io#2]
OKAY THE RIGHT REPO... anyways uhh yeah I tried to embed funi MD using Iframes but uhh... didn't work.

**Comment by PlainSys** [comment]
Okay so I figured it out... literally just embed this "https://plainsys.github.io/patches/patchsv220" lol

**Comment by dudenoob34** [comment]
wow

just

wow

![wow](https://user-images.githubusercontent.com/104111841/208138303-d0c6a6c4-ec6e-4390-b003-d8e8e4708d64.gif)
